services:
  web:
    image: kr1sp1n/doomtown
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ADMINKEY=test1234
      - DB=/doomtown.sqlite
      - FILES=/files
    volumes:
      - $PWD/files:/files
      - $PWD/doomtown.sqlite:/doomtown.sqlite